(library (trivial)
  (export main)
;  (import (wtf))
  (define (fact n)
    ; (if (zero? n)
    (if (eq? n 0) 1 (* n (fact (- n 1)))
  ))

  (define (main) 
   	; (fact (i32.const 0))
    ; (fact (i32-load 0)) 
    ; (fact (teste)) 
    (write 42)
    (write 'Hello-World)
;    ('hi) ; 'Could not find item'
    (display "Hello World")
;    (fact 5)
  )

)
